
CREATE TABLE item(
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	name varchar2(100) UNIQUE,
	price NUMBER,
	total_number NUMBER,
	PRIMARY key(id)
);

INSERT INTO item (name, price, total_number) VALUES ('iPhone', 1000, 20);

SELECT * FROM item;

INSERT INTO item (name, price, total_number) VALUES ('book', 50, 30);

insert into item (name, price, total_number)
values ('tessssttttt', 10, 5);



CREATE TABLE item_details (

	id NUMBER PRIMARY KEY ,
	description varchar2(250),
	issue_date DATE,
	expiry_date DATE,
	item_id NUMBER NOT NULL UNIQUE,
	
	CONSTRAINT item_fk FOREIGN KEY (item_id) REFERENCES item (id)
);

CREATE TABLE USERS (
	id NUMBER PRIMARY KEY ,
	name varchar2(100) CONSTRAINT name_nn NOT NULL ,
	email varchar2(50),
	password varchar2(20) CONSTRAINT password_nn NOT NULL,
	
	CONSTRAINT email_unique UNIQUE (email)
);


ALTER TABLE item ADD deleted number(1) DEFAULT 0;
