
CREATE TABLE item(
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	name varchar2(100) UNIQUE,
	price NUMBER,
	total_number NUMBER,
	PRIMARY key(id)
);

INSERT INTO item (name, price, total_number) VALUES ('iPhone', 1000, 20);

SELECT * FROM item;

INSERT INTO item (name, price, total_number) VALUES ('book', 50, 30);

insert into item (name, price, total_number)
values ('tessssttttt', 10, 5);


DROP TABLE item_details;

CREATE TABLE item_details (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    description VARCHAR2(250),
    issue_date DATE,
    expiry_date DATE,
    item_id NUMBER NOT NULL UNIQUE,
    PRIMARY KEY (id),
    CONSTRAINT item_details_fk FOREIGN KEY (item_id) REFERENCES item(id)
);

DROP TABLE users;

CREATE TABLE USERS (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(20) NOT NULL,
    PRIMARY KEY (id)
);


ALTER TABLE item ADD deleted number(1) DEFAULT 0;